### ISSUE TITLE
1.20 version requires minecraft between 1.19.3 and 1.19.4

### ISSUE THREAD

**Issue by maxutka99** [Oth3r/DirectionHUD-F#6]
[00:07:29] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'DirectionHUD' (directionhud) v1.3.3+1.20 with any version that is compatible with:
		 - minecraft 1.20
Unmet dependency listing:
	 - Mod 'DirectionHUD' (directionhud) v1.3.3+1.20 requires any version between 1.19.3 (inclusive) and 1.19.4 (inclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.20!

**Comment by Oth3r** [comment]
sorry about that 😅
fixed in [v1.3.4+1.20](https://github.com/Oth3r/DirectionHUD-Fabric/releases/tag/v1.3.4%2B1.20)
